scss_files: '_sass/*.scss'

linters:
  ColorVariable:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  VendorPrefix:
    enabled: false
