# Site Config

name: KawaiiBot
title: KawaiiBot
description: Default description

themecolour: "#f09de3"

domain: "https://kawaiibot.xyz"
baseurl: ""
url: "https://kawaiibot.xyz"
encoding: utf-8

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed
